# wrangler.toml
name = "portfolio-api"
main = "src/Api.ts" 
compatibility_date = "2024-01-01"

[vars]
# The API worker needs this to know where to verify the auth_token cookie
AUTH_WORKER_URL = "https://auth.syn-forge.com"

[[d1_databases]]
binding = "DB"
database_name = "my-personal-portfolio"
database_id = "6663c46e-f2ab-4da4-9af0-ccd03afcb3e3"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "personal-portfolio"

[[routes]]
pattern = "personal-portfolio.syn-forge.com"
custom_domain = true